import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body>
        <div className="navbar">
          <Link href="/">Home</Link>
          <Link href="/list">List</Link>  
        </div>
        {/* 칠드런 위에표시 공용용페이지로 나옴, 링크는 a태그대신씀 부드러움 */}
        {children}
      </body>
    </html>
  )
} 